name: Greeter

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thank you very much for taking the time to create an issue, if your issue is critical please tag maintainer, someone will come and resolve your issue...Thank You!'
        pr-message: 'Thanks for your Pull Request, you are an important contributor to us. Hoping that you learnt something with creating your first issue here. Someone will review your Pull request in a while. Thank You!'
